alg: ''
backbone: srnet
batch_size: 8
cover_folder_name: BossBase-1.01-cover
data_path: /home/lucas/Documents/Master Data Science/S1/Research_project/JIN_SRNet/
decoder: NR
epochs: 50
eps: 1.0e-07
gpus: '0'
in_channels: 0
lr: 0.001
lr_scheduler_name: onecycle
num_workers: 6
optimizer_name: adamax
pair_constraint: 0
payload: 0_003bis_qe
qf: ''
qf2: ''
resume_from_checkpoint: null
save: 0
seed: /home/lucas/Documents/Master Data Science/S1/Research_project/LogFiles/0_0025/srnet/RJCA/checkpoints/epoch=09_val_acc=0.9152.ckpt
size: ''
stego_folder_name: stego
surgery: ''
version: RJCA
weight_decay: 0.0002
